name: fenics2
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - anyio=3.5.0=py310h06a4308_0
  - aom=3.5.0=h27087fc_0
  - argon2-cffi=20.1.0=py310h7f8727e_1
  - asttokens=2.0.5=pyhd3eb1b0_0
  - attrs=22.1.0=py310h06a4308_0
  - babel=2.9.1=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - bcrypt=4.3.0=py310h4aa5aa6_0
  - beautifulsoup4=4.11.1=py310h06a4308_0
  - binutils_impl_linux-64=2.39=he00db2b_1
  - binutils_linux-64=2.39=h5fc0e48_11
  - biopython=1.80=py310h5764c6d_0
  - bleach=4.1.0=pyhd3eb1b0_0
  - blosc=1.21.0=h4ff587b_1
  - boost-cpp=1.74.0=h75c5d50_8
  - brotli=1.0.9=h166bdaf_8
  - brotli-bin=1.0.9=h166bdaf_8
  - brotlipy=0.7.0=py310h7f8727e_1002
  - brunsli=0.1=h2531618_0
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.18.1=h7f98852_0
  - ca-certificates=2025.4.26=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - certifi=2025.4.26=pyhd8ed1ab_0
  - cffi=1.15.1=py310h5eee18b_3
  - cfitsio=3.470=h5893167_7
  - cftime=1.6.2=py310hde88566_1
  - charls=2.2.0=h2531618_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.0.4=py310h06a4308_0
  - cloudpickle=2.2.1=py310h06a4308_0
  - cmake=3.25.0=h816a3e0_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - contourpy=1.0.6=py310hbf28c38_0
  - cryptography=39.0.1=py310h9ce1e76_2
  - curl=7.86.0=h2283fc2_1
  - cycler=0.11.0=pyhd8ed1ab_0
  - cytoolz=0.12.0=py310h5eee18b_0
  - dask-core=2023.6.0=py310h06a4308_0
  - debugpy=1.5.1=py310h295c915_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - dill=0.3.7=py310h06a4308_0
  - double-conversion=3.2.0=h27087fc_1
  - eigen=3.4.0=h4bd325d_0
  - entrypoints=0.4=py310h06a4308_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.5.0=h27087fc_0
  - fasteners=0.17.3=pyhd8ed1ab_0
  - fenics=2019.1.0=py310hff52083_30
  - fenics-dijitso=2019.1.0=py310hff52083_30
  - fenics-dolfin=2019.1.0=py310h583d6c0_30
  - fenics-ffc=2019.1.0=py310hff52083_30
  - fenics-fiat=2019.1.0=py310hff52083_30
  - fenics-libdolfin=2019.1.0=hd78bcf9_30
  - fenics-ufl=2019.1.0=py310hff52083_30
  - ffmpeg=4.4.2=gpl_hc51e5dc_110
  - fftw=3.3.10=mpi_mpich_h3e343da_5
  - fltk=1.3.8=h83e168f_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.1=hc2a2eb6_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.38.0=py310h5764c6d_1
  - freeimage=3.18.0=h530e30e_10
  - freetype=2.12.1=hca18f0e_1
  - fsspec=2023.4.0=py310h06a4308_0
  - gcc_impl_linux-64=10.4.0=h5231bdf_19
  - gcc_linux-64=10.4.0=h9215b83_11
  - gettext=0.21.1=h27087fc_0
  - giflib=5.2.1=h5eee18b_3
  - gl2ps=1.4.2=h0708190_0
  - gmp=6.2.1=h58526e2_0
  - gmpy2=2.1.2=py310h3ec546c_1
  - gmsh=4.11.0=hc719622_0
  - gnutls=3.7.8=hf3e180e_0
  - griddataformats=1.0.1=pyhd8ed1ab_0
  - gsd=2.7.0=py310hde88566_0
  - gxx_impl_linux-64=10.4.0=h5231bdf_19
  - gxx_linux-64=10.4.0=h6e491c6_11
  - h5py=3.7.0=nompi_py310h06dffec_100
  - hdf4=4.2.15=h9772cbc_5
  - hdf5=1.12.1=mpi_mpich_h5d83325_4
  - hypre=2.25.0=mpi_mpich_hed3a557_0
  - icu=70.1=h27087fc_0
  - idna=3.4=py310h06a4308_0
  - imagecodecs=2021.8.26=py310hecf7e94_1
  - imageio=2.26.0=py310h06a4308_0
  - imath=3.1.6=h6239696_1
  - importlib-metadata=6.0.0=py310h06a4308_0
  - ipykernel=6.15.2=py310h06a4308_0
  - ipython=8.7.0=py310h06a4308_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - jedi=0.18.1=py310h06a4308_1
  - jinja2=3.1.2=py310h06a4308_0
  - joblib=1.2.0=pyhd8ed1ab_0
  - jpeg=9e=h166bdaf_2
  - json5=0.9.6=pyhd3eb1b0_0
  - jsoncpp=1.9.5=h4bd325d_1
  - jsonschema=4.16.0=py310h06a4308_0
  - jupyter_client=7.4.7=py310h06a4308_0
  - jupyter_core=4.11.2=py310h06a4308_0
  - jupyter_server=1.18.1=py310h06a4308_0
  - jupyterlab=3.5.0=py310h06a4308_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.16.3=py310h06a4308_0
  - jxrlib=1.1=h7f98852_2
  - kernel-headers_linux-64=2.6.32=he073ed8_15
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.4=py310hbf28c38_1
  - krb5=1.19.3=h08a2579_0
  - lame=3.100=h166bdaf_1003
  - lazy_loader=0.1=py310h06a4308_0
  - lcms2=2.14=h6ed2654_0
  - ld_impl_linux-64=2.39=hcc3a1bd_1
  - lerc=3.0=h295c915_0
  - libaec=1.0.4=he6710b0_1
  - libblas=3.9.0=16_linux64_openblas
  - libbrotlicommon=1.0.9=h166bdaf_8
  - libbrotlidec=1.0.9=h166bdaf_8
  - libbrotlienc=1.0.9=h166bdaf_8
  - libcblas=3.9.0=16_linux64_openblas
  - libcurl=7.86.0=h2283fc2_1
  - libdeflate=1.8=h7f8727e_5
  - libdrm=2.4.114=h166bdaf_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libffi=3.4.2=h7f98852_5
  - libgcc-devel_linux-64=10.4.0=hd38fd1e_19
  - libgcc-ng=12.2.0=h65d4601_19
  - libgfortran-ng=12.2.0=h69a702a_19
  - libgfortran5=12.2.0=h337968e_19
  - libglu=9.0.0=he1b5a44_1001
  - libgomp=12.2.0=h65d4601_19
  - libiconv=1.17=h166bdaf_0
  - libidn2=2.3.4=h166bdaf_0
  - liblapack=3.9.0=16_linux64_openblas
  - libnetcdf=4.8.1=mpi_mpich_hcdf9059_2
  - libnghttp2=1.47.0=hff17c54_1
  - libnsl=2.0.0=h7f98852_0
  - libogg=1.3.4=h7f98852_1
  - libopenblas=0.3.21=pthreads_h78a6416_3
  - libpciaccess=0.17=h166bdaf_0
  - libpng=1.6.39=h753d276_0
  - libraw=0.20.2=h9772cbc_2
  - libsanitizer=10.4.0=h5246dfb_19
  - libsodium=1.0.18=h7b6447c_0
  - libsqlite=3.40.0=h753d276_0
  - libssh2=1.10.0=hf14f497_3
  - libstdcxx-devel_linux-64=10.4.0=hd38fd1e_19
  - libstdcxx-ng=12.2.0=h46fd767_19
  - libtasn1=4.19.0=h166bdaf_0
  - libtheora=1.1.1=h7f98852_1005
  - libtiff=4.4.0=hecacb30_2
  - libunistring=0.9.10=h7f98852_0
  - libuuid=2.32.1=h7f98852_1000
  - libuv=1.44.2=h166bdaf_0
  - libva=2.16.0=h166bdaf_0
  - libvorbis=1.3.7=h9c3ff4c_0
  - libvpx=1.11.0=h9c3ff4c_3
  - libwebp=1.2.4=h11a3e52_1
  - libwebp-base=1.2.4=h166bdaf_0
  - libxcb=1.13=h7f98852_1004
  - libxml2=2.10.3=h7463322_0
  - libzip=1.9.2=hc929e4a_1
  - libzlib=1.2.13=h166bdaf_4
  - libzopfli=1.0.3=he6710b0_0
  - locket=1.0.0=py310h06a4308_0
  - loguru=0.6.0=py310hff52083_2
  - lz4-c=1.9.3=h9c3ff4c_1
  - markupsafe=2.1.1=py310h7f8727e_0
  - matplotlib-base=3.6.2=py310h8d5ebf3_0
  - matplotlib-inline=0.1.6=py310h06a4308_0
  - mdanalysis=2.3.0=py310h6f6d519_1
  - metis=5.1.0=h58526e2_1006
  - mistune=0.8.4=py310h7f8727e_1000
  - mmtf-python=1.1.3=pyhd8ed1ab_0
  - mpc=1.2.1=h9f54685_0
  - mpfr=4.1.0=h9202a9a_1
  - mpi=1.0=mpich
  - mpi4py=3.1.4=py310h37cc914_0
  - mpich=4.0.3=h846660c_100
  - mpmath=1.2.1=pyhd8ed1ab_0
  - mrcfile=1.4.3=pyhd8ed1ab_0
  - msgpack-python=1.0.4=py310hbf28c38_1
  - mshr=2019.1.0=py310hffed6ae_5
  - mumps-include=5.2.1=ha770c72_11
  - mumps-mpi=5.2.1=h7ee95aa_11
  - munkres=1.1.4=pyh9f0ad1d_0
  - natsort=7.1.1=pyhd3eb1b0_0
  - nbclassic=0.4.8=py310h06a4308_0
  - nbclient=0.5.13=py310h06a4308_0
  - nbconvert=6.4.4=py310h06a4308_0
  - nbformat=5.7.0=py310h06a4308_0
  - ncurses=6.3=h27087fc_1
  - nest-asyncio=1.5.5=py310h06a4308_0
  - netcdf4=1.6.0=nompi_py310h947f774_100
  - nettle=3.8.1=hc379101_1
  - networkx=2.8.8=pyhd8ed1ab_0
  - notebook=6.5.2=py310h06a4308_0
  - notebook-shim=0.2.2=py310h06a4308_0
  - numpy=1.23.5=py310h53a5b5f_0
  - occt=7.6.3=h665cfa0_0
  - openexr=3.1.5=he0ac6c6_1
  - openh264=2.3.1=h27087fc_1
  - openjpeg=2.5.0=h7d73246_1
  - openssl=3.3.1=h4bc722e_2
  - p11-kit=0.24.1=hc5aa10d_0
  - packaging=21.3=pyhd8ed1ab_0
  - pandas=1.5.2=py310h769672d_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - paramiko=3.5.0=py310h06a4308_0
  - parmetis=4.0.3=h2a9763c_1005
  - parso=0.8.3=pyhd3eb1b0_0
  - partd=1.2.0=pyhd3eb1b0_1
  - patsy=0.5.3=pyhd8ed1ab_0
  - petsc=3.17.3=real_h6ce3b2e_100
  - petsc4py=3.17.3=real_h5faf7bb_101
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.2.0=py310h454ad03_3
  - pip=22.3.1=pyhd8ed1ab_0
  - pkg-config=0.29.2=h36c2ea0_1008
  - pkgconfig=1.5.5=pyhd8ed1ab_4
  - proj=9.0.1=h93bde94_1
  - prometheus_client=0.14.1=py310h06a4308_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - psutil=5.9.0=py310h5eee18b_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptscotch=6.0.9=hb499603_2
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pugixml=1.11.4=h9c3ff4c_0
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pybind11=2.9.2=py310h3c18c91_0
  - pybind11-global=2.10.1=py310hbf28c38_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pynacl=1.5.0=py310h5eee18b_1
  - pyopenssl=23.0.0=py310h06a4308_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyrsistent=0.18.0=py310h7f8727e_0
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.8=h4a9ceb5_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.16.2=py310h06a4308_0
  - python-gmsh=4.11.0=h57928b3_0
  - python_abi=3.10=3_cp310
  - pytz=2022.6=pyhd8ed1ab_0
  - pywavelets=1.4.1=py310h5eee18b_0
  - pyyaml=6.0=py310h5eee18b_1
  - pyzmq=23.2.0=py310h6a678d5_0
  - rapidjson=1.1.0=he1b5a44_1002
  - readline=8.1.2=h0f457ee_0
  - requests=2.28.1=py310h06a4308_0
  - rhash=1.4.3=h166bdaf_0
  - scalapack=2.2.0=hd931219_1
  - scikit-image=0.20.0=py310h6a678d5_0
  - scikit-learn=1.1.3=py310h0c3af53_1
  - scipy=1.9.3=py310hdfbd76f_2
  - scotch=6.0.9=hb2e6521_2
  - seaborn=0.12.1=hd8ed1ab_0
  - seaborn-base=0.12.1=pyhd8ed1ab_0
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=65.5.1=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - slepc=3.17.1=real_ha2e80f3_102
  - slepc4py=3.17.1=real_h7df52cc_103
  - snappy=1.1.9=h295c915_0
  - sniffio=1.2.0=py310h06a4308_1
  - soupsieve=2.3.2.post1=py310h06a4308_0
  - sqlite=3.40.0=h4ff8645_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - statsmodels=0.13.5=py310hde88566_2
  - suitesparse=5.10.1=h9e50725_1
  - superlu=5.2.2=h00795ac_0
  - superlu_dist=7.2.0=h25dcc4a_0
  - svt-av1=1.3.0=h27087fc_0
  - sympy=1.11.1=py310hff52083_2
  - sysroot_linux-64=2.12=he073ed8_15
  - tbb=2021.7.0=h924138e_0
  - tbb-devel=2021.7.0=h924138e_0
  - terminado=0.13.1=py310h06a4308_0
  - testpath=0.6.0=py310h06a4308_0
  - threadpoolctl=3.1.0=pyh8a188c0_0
  - tidynamics=1.0.0=py_0
  - tifffile=2021.7.2=pyhd3eb1b0_2
  - tk=8.6.12=h27826a3_0
  - tomli=2.0.1=py310h06a4308_0
  - toolz=0.12.0=py310h06a4308_0
  - tornado=6.2=py310h5eee18b_0
  - tqdm=4.64.1=pyhd8ed1ab_0
  - traitlets=5.7.1=py310h06a4308_0
  - typing_extensions=4.4.0=pyha770c72_0
  - tzdata=2022g=h191b570_0
  - unicodedata2=15.0.0=py310h5764c6d_0
  - urllib3=1.26.13=py310h06a4308_0
  - utfcpp=3.2.2=ha770c72_0
  - vtk=9.1.0=egl_py310ha29738a_11
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py310h06a4308_1
  - websocket-client=0.58.0=py310h06a4308_4
  - wheel=0.38.4=pyhd8ed1ab_0
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xorg-fixesproto=5.0=h7f98852_1002
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.7.2=h7f98852_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxmu=1.1.3=h7f98852_0
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-libxt=1.2.1=h7f98852_2
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - zeromq=4.3.4=h2531618_0
  - zfp=0.5.5=h295c915_6
  - zipp=3.11.0=py310h06a4308_0
  - zlib=1.2.13=h166bdaf_4
  - zstd=1.5.2=h6239696_4
prefix: /home1/08016/tg873155/miniconda3/envs/fenics2
